# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e7e1de"

# Title color for boxes
theme[title]="#dbc2ac"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d2c4b9"

# Background color of selected item in processes box
theme[selected_bg]="#dbc2ac"

# Foreground color of selected item in processes box
theme[selected_fg]="#3d2d1e"

# Color of inactive/disabled text
theme[inactive_fg]="#d1c4ba"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#bac9d0"

# Cpu box outline color
theme[cpu_box]="#9a8f86"

# Memory/disks box outline color
theme[mem_box]="#9a8f86"

# Net up/down box outline color
theme[net_box]="#9a8f86"

# Processes box outline color
theme[proc_box]="#9a8f86"

# Box divider line and small boxes line color
theme[div_line]="#4e453e"

# Temperature graph colors
theme[temp_start]="#d2c4b9"
theme[temp_mid]="#dbc2ac"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d2c4b9"
theme[cpu_mid]="#dbc2ac"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d2c4b9"
theme[free_mid]=""
theme[free_end]="#51473f"

# Mem/Disk cached meter
theme[cached_start]="#bac9d0"
theme[cached_mid]=""
theme[cached_end]="#66747b"

# Mem/Disk available meter
theme[available_start]="#dbc2ac"
theme[available_mid]=""
theme[available_end]="#826e5b"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#d2c4b9"
theme[download_mid]="#dbc2ac"
theme[download_end]="#bac9d0"

# Upload graph colors
theme[upload_start]="#d2c4b9"
theme[upload_mid]="#dbc2ac"
theme[upload_end]="#bac9d0"