# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0e3de"

# Title color for boxes
theme[title]="#8fd6ab"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b1cdb9"

# Background color of selected item in processes box
theme[selected_bg]="#8fd6ab"

# Foreground color of selected item in processes box
theme[selected_fg]="#003921"

# Color of inactive/disabled text
theme[inactive_fg]="#bfc9c0"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#ffb2b8"

# Cpu box outline color
theme[cpu_box]="#89938b"

# Memory/disks box outline color
theme[mem_box]="#89938b"

# Net up/down box outline color
theme[net_box]="#89938b"

# Processes box outline color
theme[proc_box]="#89938b"

# Box divider line and small boxes line color
theme[div_line]="#404942"

# Temperature graph colors
theme[temp_start]="#b1cdb9"
theme[temp_mid]="#8fd6ab"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b1cdb9"
theme[cpu_mid]="#8fd6ab"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b1cdb9"
theme[free_mid]=""
theme[free_end]="#354f3f"

# Mem/Disk cached meter
theme[cached_start]="#ffb2b8"
theme[cached_mid]=""
theme[cached_end]="#e68f97"

# Mem/Disk available meter
theme[available_start]="#8fd6ab"
theme[available_mid]=""
theme[available_end]="#70b68d"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#b1cdb9"
theme[download_mid]="#8fd6ab"
theme[download_end]="#ffb2b8"

# Upload graph colors
theme[upload_start]="#b1cdb9"
theme[upload_mid]="#8fd6ab"
theme[upload_end]="#ffb2b8"